- name: Install packages
  become: true
  apt:
    name: ["tmux", "fzf", "gimp", "xclip", "screenkey", "tldr", "ripgrep"]
  tags:
    - install
    - productivity
- name: Check for tmux plugin manager
  stat:
    path: "~/.tmux/plugins/tpm/"
  register: tpm
- name: Install tmux plugin manager
  shell: git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  when: tpm.stat.exists == False
