- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  become: true
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  become: true
  apt:
    name: ["lua5.1", "unzip", "libtool", "libtool-bin", "gettext"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3 (the rest)
  become: true
  apt:
    name:
      [
        "curl",
        "btop",
        "golang",
        "lsof",
        "ccache",
        "ninja-build",
        "python3-pip",
        "moreutils",
        "clangd",
        "ripgrep",
      ]
  tags:
    - install
    - core

- name: Install Clang
  become: true
  apt:
    name: ["clang", "clang-11", "clang-12", "clangd", "clangd-11", "clangd-12"]
  tags:
    - install
    - neovim
    - core
- name: Get lazygit version from Github API
  command: "curl -s 'https://api.github.com/repos/jesseduffield/lazygit/releases/latest' | grep -Po '\"tag_name\": \"v\\K[^\"]*'"
  register: lazygit_version
- name: Download lazygit archive
  command: "curl -Lo lazygit.tar.gz 'https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_{{ lazygit_version.stdout }}_Linux_x86_64.tar.gz'"
  args:
    chdir: "/tmp"

- name: Extract Lazygit archive
  command: "tar xf lazygit.tar.gz lazygit"
  args:
    chdir: "/tmp"

- name: Install lazygit
  become: true
  command: "install lazygit /usr/local/bin/"
  args:
    chdir: "/tmp"
