- name: Debugger JavaScript Exists?
  stat:
    path: "{{ personal }}/microsoft-sucks/vscode-js-debug"
  register: node_debugger
  tags:
    - install
    - debugger

- name: Debugger - JavaScript
  ansible.builtin.git:
    repo: "git@github.com:microsoft/vscode-js-debug.git"
    dest: "{{ personal }}/microsoft-sucks/vscode-js-debug"
  tags:
    - install
    - debugger
  when: node_debugger.stat.exists == False

- name: Debugger npm i and build JavaScript
  shell: cd {{ personal }}/microsoft-sucks/vscode-js-debug && npm i && npm run compile
  tags:
    - install
    - debugger
