- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:sifterstudios/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles
    - stow
- name: Do the dotbot!
  shell: cd $HOME/.dotfiles && ./install
  tags:
    - install
    - dotfiles
    - stow
