- name: Install Python3
  become: true
  apt:
    name: python3
    state: present
- name: Install Python3 virtual environment
  become: true
  apt:
    name: python3-venv
    state: present
- name: Install Snapd
  become: true
  ansible.builtin.package:
    name: snapd
    state: present
